language: "ar"
reviews:
  profile: "chill" # لتقليل كثرة الملاحظات غير الهامة
  path_filters:
    - "!data/**"
    - "!**/build/**"
    - "!frontend_flutter/android/**"
    - "!frontend_flutter/ios/**"
    - "!**/__pycache__/**"
    - "!package-lock.json"
    - "!Artifacts/**" # لو مش عاوزه يراجع ملفات الـ MD
  summary:
    heading_level: 2
