version: '3.8'

services:
  maps-scraper:
    build:
      context: .
      dockerfile: services/maps_scraper/Dockerfile
    container_name: maps_scraper_service
    ports:
      - "8001:8000" # Local 8001 -> Container 8000
    volumes:
      - .:/app
      - ./config:/app/config
    environment:
      - ENV=PROD
      - CONFIG_PATH=/app/config/maps_scraper.yaml
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
    restart: always

networks:
  default:
    name: cns_network
